### ISSUE TITLE
freckle-env fails to build with envparse >=0.5.2

### ISSUE THREAD

**Issue by chris-martin** [freckle/freckle-app#219]
#199 doesn't seem to have done the job, not sure why CI missed it.

```
freckle-env    > [2 of 3] Compiling Freckle.App.Env
freckle-env    > 
freckle-env    > /tmp/nix-shell.fZXUt0/stack-90060e3cb4582795/freckle-env-0.0.1.1/library/Freckle/App/Env.hs:99:3: error: [GHC-87543]
freckle-env    >     Ambiguous occurrence ‘eitherReader’.
freckle-env    >     It could refer to
freckle-env    >        either ‘Env.eitherReader’,
freckle-env    >               imported from ‘Env’ at library/Freckle/App/Env.hs:46:1-24
freckle-env    >               (and originally defined in ‘Env.Internal.Parser’),
freckle-env    >            or ‘Freckle.App.Env.eitherReader’,
freckle-env    >               defined at library/Freckle/App/Env.hs:86:1.
freckle-env    >    |
freckle-env    > 99 |   eitherReader $
freckle-env    >    |   ^^^^^^^^^^^^
freckle-env    > 
freckle-env    > /tmp/nix-shell.fZXUt0/stack-90060e3cb4582795/freckle-env-0.0.1.1/library/Freckle/App/Env.hs:122:3: error: [GHC-87543]
freckle-env    >     Ambiguous occurrence ‘eitherReader’.
freckle-env    > [3 of 3] Compiling Paths_freckle_env
freckle-env    >     It could refer to
freckle-env    >        either ‘Env.eitherReader’,
freckle-env    >               imported from ‘Env’ at library/Freckle/App/Env.hs:46:1-24
freckle-env    >               (and originally defined in ‘Env.Internal.Parser’),
freckle-env    >            or ‘Freckle.App.Env.eitherReader’,
freckle-env    >               defined at library/Freckle/App/Env.hs:86:1.
freckle-env    >     |
freckle-env    > 122 |   eitherReader $ go . second (T.drop 1) . T.breakOn (T.singleton c) . T.pack
freckle-env    >     |   ^^^^^^^^^^^^
freckle-env    > 
freckle-env    > /tmp/nix-shell.fZXUt0/stack-90060e3cb4582795/freckle-env-0.0.1.1/library/Freckle/App/Env.hs:166:11: error: [GHC-87543]
freckle-env    >     Ambiguous occurrence ‘eitherReader’.
freckle-env    >     It could refer to
freckle-env    >        either ‘Env.eitherReader’,
freckle-env    >               imported from ‘Env’ at library/Freckle/App/Env.hs:46:1-24
freckle-env    >               (and originally defined in ‘Env.Internal.Parser’),
freckle-env    >            or ‘Freckle.App.Env.eitherReader’,
freckle-env    >               defined at library/Freckle/App/Env.hs:86:1.
freckle-env    >     |
freckle-env    > 166 | timeout = eitherReader $ parseTimeout . span isDigit
freckle-env    >     |           ^^^^^^^^^^^^
```

**Comment by pbrisbin** [comment]
Hmm, I'm confused. [lts-23 has envparse-0.6.0](https://www.stackage.org/lts-23.3/package/envparse-0.6.0) and it seems to [build fine](https://github.com/freckle/freckle-app/actions/runs/12639989972/job/35219468844?pr=220).

**Comment by chris-martin** [comment]
Hm, maybe I have some detail wrong. I've had to hold back `envparse` in https://github.com/freckle/megarepo/pull/37947 to get it to build. Once that PR is in a working state I can take another look at what happens when I try to bring `envparse` up to date.

**Comment by chris-martin** [comment]
Got fixed and then didn't get released, I think.

- by #199
